server:
  port: 8082
spring:
  application:
    name: producerAPP
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USER:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}
    virtual-host: ${RABBIT_MQ_VHOST:}
rabbit-config:
  rabbit:
    exchange:
      send: send.topic
    routingKey:
      sender: sender.routingKey
    queue:
      sender: sender.queue